# Generated by Django 3.0.4 on 2020-04-25 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200425_0222'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Manager',
        ),
    ]
